name: Deploy website
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/'
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubnutu-latest
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
